version: '3'
services:
  app:
    image: your-application-image
    environment:
      JDBC_URL: jdbc:postgresql://prod-db:5432/proddb
      JDBC_USERNAME: produser
      JDBC_PASSWORD: prodpassword
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5437:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: